### ISSUE TITLE
HackaComm Timeline update for Jan 5-7

### ISSUE THREAD

**Issue by eharason** [cusec/2021#100]
- Meet the Mentor day January 4th, hosted on Discord
- Need to be registered to the hackathon in order to be on Discord. Register today!
- Teams can register up until Jan 7th 23:59:59 (changed from Jan 5th)
    - Update WebPage Timeline + post link Description

Meet the Mentor schedule
- 1pm: HackaComm Intro
    - competition overview
    - mentor intros
    - mini prizes
- 1:30pm to 4: mentor drop ins
    - students can ask mentors any questions they may have!
- 4pm-5pm: Social (cusec - games)

**Comment by KoChris** [comment]
this looks good to me.
@sttic 

Can you add this to the HackaComm page?

1. We'd like to add the "Meet The Mentor" schedule under "January 4th - Meet the mentors day"
2. We'd like to change "January 5th - Submit your teams" to "January 5 - January 7th"
3. As the second and third top level point of January 5th, we'd like to add "Need to be registered to the hackathon in order to be on Discord. Register today!" and "Teams can register up until Jan 7th 23:59:59"

**Comment by sttic** [comment]
> this looks good to me.
> @sttic
> 
> Can you add this to the HackaComm page?
> 
> 1. We'd like to add the "Meet The Mentor" schedule under "January 4th - Meet the mentors day"
> 2. We'd like to change "January 5th - Submit your teams" to "January 5 - January 7th"
> 3. As the second and third top level point of January 5th, we'd like to add "Need to be registered to the hackathon in order to be on Discord. Register today!" and "Teams can register up until Jan 7th 23:59:59"

Yes! I'll add those
